name = "Exnovation"
uuid = "eb535ea2-a284-4d5f-a499-9e884733dc08"
authors = ["hyperpolymath"]
version = "0.1.0"

[deps]

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
